kookmin-sw/capstone-2024-13

src/docker-compose.yml, src/service/nginx/tool/setup.sh
=> [Feat] Nginx log volume mount #22

src/service/nginx/tool/certbot.sh
- close #26 
- 관련 내용 궁금하시면 TLS/SSL 키워드로 공부하시면됩니다.
- 궁금하신거 있으시면 질문주세요
-
=> [Feat] Get certification with certbot #26

src/service/nginx/tool/setup.sh
=> [Fix] AWS certificate manager #28

src/service/langserve/Dockerfile, src/service/langserve/app/chain.py, src/service/langserve/app/server.py, src/service/langserve/poetry.lock, src/service/langserve/pyproject.toml
- close #23 
- models directory 생성
- api 수정 (/docs/ 참고)
- chain.py modulization
-
-
=>  [Feat] langserve API 추가 구현 #23

src/service/langserve/Dockerfile, src/service/nextjs/src/app/(route)/chat/page.tsx, src/service/nextjs/src/app/(route)/diary/page.tsx, src/service/nextjs/src/app/(route)/page.tsx, src/service/nextjs/src/app/_component/chat/index.tsx, src/service/nextjs/src/app/_component/header/index.tsx, src/service/nextjs/src/app/_icon/index.tsx, src/service/nextjs/src/app/_style/(route)/chat/index.module.css, src/service/nextjs/src/app/_style/(route)/index.module.css, src/service/nextjs/src/app/_style/component/chat/index.module.css
=> [Feat] Chat page #31

src/service/langserve/app/chain/v3/__init__.py, src/service/langserve/app/server.py, src/service/langserve/app/util/yaml_parser/__init__.py
- close #37 
- modulization과정중에 발생한 error fix
- error fix 후 test 완료했습니다.
-
=> [Fix] langserve trouble shooting #37

src/service/langserve/app/chain/v3/__init__.py
- OPENAI_API_KEY 읽어오는중 발생한 문제
-
-
=> [FIX] OPENAI_API_KEY error #42

src/service/nextjs/src/app/_component/profile-image/image-selector/index.tsx
- 우선 이미지 허용 파일 확장자는 세개로 제한했습니다. 추후에 필요에 따라서 수정하면 될 것 같습니다.
-
-
=> [Fix] Enhance Image Upload Security by Validating File Type #46

src/service/nestjs/src/api/diary/diary.controller.ts, src/service/nestjs/src/api/diary/diary.service.ts, src/service/nestjs/src/api/diary/dto/createDiary.dto.ts, src/service/nestjs/src/common/database/schema/diary.schema.ts, src/service/nestjs/src/common/database/schema/user.schema.ts
-
- Diary CRUD API구현
- User, Diary 관계 부모 참조로 변경
=> [Fix] User, Diary Schema 구조 설계 및 수정 #18

src/service/mystic/app/server.py
- 아래 문서에서 취약점 발견
-  https://drive.google.com/file/d/1WxSV_nlz3FRE79Vh0mUECRCtaG5TtpWf/view?usp=drive_link 
- 대응책으로 server.py에서의 전처리 코드 구현
- 추후 만들어질 프롬프트 테마들에 따라서 역할 변경 감지 패턴을 다양화할 필요가 있습니다.
- JSON 파일을 따로 만들어서 처리를 하면 좋을거라 생각합니다.
-  우선 역할 변경 요청 감지를 위한 일반화된 패턴을 임의로 작성하고 테스팅한 결과 공유된 report와 비교해보았을 때, 프롬프트의 역할 변경이 되지 않음을 확인할 수 있었습니다.
- 
-
=> [Secure]Langserve Prompt Hacking Countermeasure #41

src/service/nextjs/src/app/(route)/auth/register/button.tsx, src/service/nextjs/src/app/(route)/diary/[id]/page.tsx, src/service/nextjs/src/app/(route)/diary/page.tsx, src/service/nextjs/src/app/(route)/mypage/profile/index.tsx, src/service/nextjs/src/app/_component/chat/index.tsx, src/service/nextjs/src/app/_component/profile-image/index.tsx, src/service/nextjs/src/app/_component/tab-bar/button/index.tsx, src/service/nextjs/src/app/_style/(route)/diary/[id]/index.module.css, src/service/nextjs/src/app/_style/(route)/diary/index.module.css, src/service/nextjs/src/app/_style/(route)/mypage/button-group/index.module.css, src/service/nextjs/src/app/_style/(route)/mypage/profile/index.module.css, src/service/nextjs/src/app/_style/component/chat/index.module.css, src/service/nextjs/src/app/_style/component/profile-image/index.module.css
=> [Feat] Diary page #59

src/service/nestjs/src/api/diary/diary.controller.ts, src/service/nestjs/src/api/diary/diary.service.ts, src/service/nestjs/src/api/diary/dto/index.ts, src/service/nestjs/src/api/diary/dto/request/diary/index.ts, src/service/nestjs/src/api/diary/dto/request/find/index.ts, src/service/nestjs/src/api/diary/dto/request/index.ts, src/service/nestjs/src/common/database/schema/diary.schema.ts
- DTO 양식을 일관성 있게 맞추기 위해서 수정하였다
-
- 검색하는 함수들을 find 함수를 오버라이딩해서 재사용성을 높여주었다.
=> [Fix] DiaryDTO 수정 및 Diary 쿼리 함수 변경 #60

src/service/mystic/app/server.py, src/service/nestjs/src/api/mystic/dto/request/connect/index.ts, src/service/nestjs/src/api/mystic/dto/request/index.ts, src/service/nestjs/src/api/mystic/mystic.controller.ts, src/service/nestjs/src/api/mystic/mystic.service.ts, src/service/nextjs/src/app/(route)/diary/[id]/page.tsx, src/service/nextjs/src/app/(route)/diary/page.tsx, src/service/nextjs/src/app/_service/postConnectMystic.ts
=> [Fix] Diary page with mystic API #71

src/service/nextjs/src/app/(route)/diary/[id]/page.tsx
=> [Fix] Profile image id

src/service/nestjs/src/api/album/album.controller.ts, src/service/nestjs/src/api/album/album.service.ts, src/service/nestjs/src/api/auth/auth.controller.ts, src/service/nestjs/src/api/auth/google-oauth2/google-oauth2.strategy.ts, src/service/nestjs/src/api/diary/diary.controller.ts, src/service/nestjs/src/api/diary/diary.service.ts, src/service/nestjs/src/api/image/service/s3.service.ts, src/service/nestjs/src/api/mystic/mystic.service.ts, src/service/nestjs/src/api/test/test.controller.ts, src/service/nestjs/src/common/database/schema/album.schema.ts, src/service/nestjs/src/common/database/schema/diary.schema.ts, src/service/nestjs/src/common/database/schema/user.schema.ts, src/service/nextjs/src/app/_service/api/deleteFetcher.ts, src/service/nextjs/src/app/_service/api/getFetcher.ts, src/service/nextjs/src/app/_service/api/patchFetcher.ts, src/service/nextjs/src/app/_service/api/postFetcher.ts, src/service/nextjs/src/app/_service/api/putFetcher.ts, src/service/nextjs/src/app/_service/postConnectMystic.ts, src/service/nextjs/src/app/_service/postInvokeChat.ts, src/service/nextjs/src/app/_service/postPresignedUrl.ts, src/service/nextjs/src/app/_service/postRegister.ts
- 개발을 하실 때 타입 스크립트 특성상 type 선언을 명시적으로 하지 않았을 때, any type으로 암시적 선언이 됩니다. 하지만, any type이라고 해도 명시적으로 선언을 해주셔야 코드 가독성과 디버깅 시 더 효율적입니다.
- 또한 any 타입은 최대한 지양해야 하는데요 아래는 제가 서치를 통해서 알게된 any type 사용시 발생가능한 문제점들입니다. 참고하시면 좋을거 같아요.
- 1. any타입을 사용하면 타입 체커와 타입스크립트 언어 서비스를 무력화시킨다.
- 2. any타입은 진짜 문제점을 감추고 개발경험을 나쁘게하고, 타입 시스템의 신뢰도를 떨어뜨린다.
제가 수정한 부분에서 문제가 있거나 피드백 주시면 감사하겠습니다.
- any 타입 선언을 명시적으로 해주었고, 추가로 다른 type 선언이 필요하다고 생각한 부분은 그에 맞게 수정했습니다.
-
=> [Secure] 암시적 any type 수정 #80

README.md
=> [Feat] README.md #85

src/service/nextjs/src/app/(route)/album/[id]/diary/index.tsx, src/service/nextjs/src/app/_component/meetballs-menu/index.tsx, src/service/nextjs/src/app/_style/(route)/album/[id]/diary/index.module.css, src/service/nextjs/src/app/_style/component/meetballs-menu/index.module.css
- close #89 
- 
-
- 현재 Album에서 Meatballs menu를 임시로 테스트해봤는데, 추후 앨범에서 일기를 클릭하여 나오는 일기 상세 페이지가 구현되면 그 곳으로 이전할 예정입니다.
=> [Feat] Meatballs menu component #89

src/service/nextjs/public/manifest.webmanifest, src/service/nextjs/src/app/(route)/(private)/diary/page.tsx, src/service/nextjs/src/app/(route)/(private)/layout.tsx, src/service/nextjs/src/app/(route)/(private)/search/page.tsx, src/service/nextjs/src/app/(route)/layout.tsx, src/service/nextjs/src/app/_context/tab-bar-visibility/index.tsx
=> [Fix] Layout #101

src/service/nextjs/src/app/(route)/(private)/diary/page.tsx, src/service/nextjs/src/app/(route)/(private)/layout.tsx, src/service/nextjs/src/app/(route)/(private)/search/page.tsx, src/service/nextjs/src/app/_context/tab-bar-visibility/index.tsx, src/service/nextjs/src/app/_style/component/tab-bar/index.module.css
- close #103
- 바닥면에 닿을 때, TabBar가 사라지며 UI size가 바뀌는데, 사이즈가 바뀜으로 인해 scroll값이 변한다.
- 그 scroll값에 의해 다시 TabBar의 visibility가 변하는 무한 루프 현상이 생긴다.
- 이를 scrollBottom 값을 설정하므로써 해결하였다.
-
=> [Fix] TabBar visibility #103

src/service/nextjs/src/app/(route)/(private)/album/album-component/index.tsx, src/service/nextjs/src/app/(route)/(private)/album/create-album-button/index.tsx, src/service/nextjs/src/app/(route)/(private)/album/create-album/index.tsx, src/service/nextjs/src/app/(route)/(private)/diary/icon/index.tsx, src/service/nextjs/src/app/(route)/(private)/diary/page.tsx, src/service/nextjs/src/app/(route)/(private)/layout.tsx, src/service/nextjs/src/app/(route)/(private)/mypage/edit-button/index.tsx, src/service/nextjs/src/app/(route)/(private)/search/page.tsx, src/service/nextjs/src/app/(route)/(public)/auth/register/button.tsx, src/service/nextjs/src/app/_component/google-login/icon.tsx, src/service/nextjs/src/app/_component/hamburger-menu/index.tsx, src/service/nextjs/src/app/_component/header/index.tsx, src/service/nextjs/src/app/_component/meetballs-menu/index.tsx, src/service/nextjs/src/app/_component/modal/index.tsx, src/service/nextjs/src/app/_component/tab-bar/button/index.tsx, src/service/nextjs/src/app/_context/tab-bar-visibility/index.tsx, src/service/nextjs/src/app/_icon/index.tsx
- close #105 
- Tab으로 criteria를 바꾸니 이슈 없이 잘 작동하네요
-
=> [Fix] TabBar visibility #105

src/service/nextjs/src/app/(route)/(private)/diary/page.tsx, src/service/nextjs/src/app/(route)/(private)/diary/theme-select/index.tsx, src/service/nextjs/src/app/(route)/(private)/diary/theme-select/theme/index.tsx, src/service/nextjs/src/app/_style/(route)/(private)/diary/theme-select/index.module.css, src/service/nextjs/src/app/_style/(route)/(private)/diary/theme-select/theme/index.module.css
=> [Feat] Theme select page #107

src/service/nextjs/yarn.lock
=> [Feat] Add sharp module

src/service/nextjs/next.config.js, src/service/nextjs/public/sw.js, src/service/nextjs/src/app/page.tsx
=> [Feat] Apply PWA #122

src/service/nextjs/.gitignore, src/service/nextjs/src/service/index.ts
=> [Fix] patchMe

src/service/nextjs/src/service/index.ts
=> [Fix] Add to postLogout to service

src/service/mystic/Dockerfile, src/service/mystic/poetry.lock, src/service/mystic/pyproject.toml
=> [Fix] Dockerize TTS #146

src/service/mongodb/tool/initdb.sh, src/service/nestjs/src/api/diary/diary.controller.ts, src/service/nextjs/next.config.js, src/service/nextjs/src/app/(private)/album/[albumId]/diary/[diaryId]/page.tsx, src/service/nextjs/src/app/(private)/album/[albumId]/page.tsx, src/service/nextjs/src/app/(private)/search/diary/[id]/page.tsx, src/service/nextjs/src/app/(private)/search/page.tsx, src/service/nextjs/src/service/getRandomDiary.ts, src/service/nextjs/src/service/index.ts, src/service/nextjs/src/service/patchProfileImage.ts, src/service/nextjs/src/service/postRandomDiary.ts
- close #135 
- 걸어주신 이슈 작업 마쳤습니다.
- PR review 해주시면 merge 하겠습니다.
- 다른 Secure issue도 open 해주세요.
-
=> [Secure] IDOR Vulnerability report #135

src/service/mystic/app/router/llm/__init__.py, src/service/mystic/app/router/llm/chat.py, src/service/mystic/app/router/llm/connect.py, src/service/mystic/app/router/llm/disconnect.py, src/service/mystic/app/router/stt/__init__.py, src/service/mystic/app/router/tts/__init__.py, src/service/mystic/app/server.py, src/service/mystic/chain/base/__init__.py, src/service/mystic/model/tts/basic/__init__.py
- close #151 
- Error Fix and Test by Swagger Docs
- Error 수정했습니다.
- Import Error나는 부분들을 수정했는데 Python이 버전마다 Import하는 방법이 달라서 본인 Test version에 맞게 module import시에 '.'을 빼야할 수도 있습니다.
- ex) from . import connect -> import connect
=> [Fix] Dockerize후 error fix #151

src/service/mystic/src/app/router/llm/__init__.py, src/service/mystic/src/app/router/llm/connect.py, src/service/mystic/src/app/router/llm/disconnect.py, src/service/mystic/src/app/router/llm/image.py, src/service/mystic/src/app/util/image_captioner/__init__.py, src/service/mystic/src/chain/base/__init__.py, src/service/mystic/src/template/meta.xml, src/service/nestjs/src/api/mystic/dto/index.ts, src/service/nestjs/src/api/mystic/dto/request/upload-image/index.ts, src/service/nestjs/src/api/mystic/dto/response/connect/index.ts, src/service/nestjs/src/api/mystic/dto/response/index.ts, src/service/nestjs/src/api/mystic/dto/response/upload-image/index.ts, src/service/nestjs/src/api/mystic/mystic.controller.ts, src/service/nestjs/src/api/mystic/mystic.service.ts
=> [Fix] Connect & Image captioning 분리 #165

src/service/nestjs/src/api/album/album.service.ts, src/service/nestjs/src/api/diary/diary.service.ts, src/service/nestjs/src/api/user/user.controller.ts, src/service/nextjs/src/app/(private)/album/[albumId]/diary/[diaryId]/page.tsx, src/service/nextjs/src/app/(private)/album/[albumId]/page.tsx, src/service/nextjs/src/app/(private)/diary/page.tsx, src/service/nextjs/src/app/(private)/search/diary/[id]/page.tsx, src/service/nextjs/src/app/(private)/search/page.tsx, src/service/nextjs/src/container/(private)/search/search-bar/index.tsx, src/service/nextjs/src/service/postFindUserById.ts, src/service/nextjs/src/service/postSearchDiary.ts, src/service/nextjs/src/style/app/(private)/album/[albumId]/index.module.css, src/service/nextjs/src/style/component/header/index.module.css
- close #172 
- 앨범 삭제하기도 추가로 작성했습니다. 분리 못해서 죄송합니다.
-
=> [Feat] Search page API #172

src/service/nextjs/src/container/(private)/album/create-album/index.tsx, src/service/nextjs/src/style/container/(private)/album/create-album/index.module.css
- close #124 
- 10자 이하로만 설정 가능하게 구현하였습니다
- 한글은 10자가 최대이고, 영어는 더 길어도 될 것 같은데 이거 은근 고민되네요
- 이런 경우 흔한 경우일테니 같이 검색해주시고 머리 맞대주세요
-
=> [Debug] Album page title bug #124

src/service/mystic/src/app/router/llm/chat.py, src/service/mystic/src/app/router/llm/connect.py, src/service/mystic/src/chain/v3/__init__.py, src/service/mystic/src/template/meta.xml
- 종료 기능 구현
- close #183 
- 학생이 종료를 원할때 LLM이 "종료"를 출력하도록 prompt 수정
- LLM이 "종료"를 출력하면 response.content를 'END'로 바꿔서 return
- test 완료
-
=> [Feat] 종료 기능 구현 #183

src/service/mystic/src/template/character.yml
=> [Fix] character 별로 prompt가 들어간 character.yml 수정 #164

src/service/mystic/src/app/router/llm/chat.py, src/service/mystic/src/app/router/llm/connect.py, src/service/mystic/src/chain/base/__init__.py, src/service/mystic/src/template/diary.xml, src/service/mystic/src/template/meta.xml
-
- summary api를 만들어 api 호출 시에 connection의 해당 id에 있는 대화를 가져와서 요약하는 방식입니다.
- 아래는 결과입니다.
~~~
Conversation
AI: 안녕하세요! 오늘 어떤 이야기를 들려주실 건가요?
Human: 오늘은 동물원에 갔다왔어요.
AI: 와, 동물원에 가다니 정말 재미있겠네요! 어떤 동물들을 보셨나요? 어떤 경험이 가장 인상 깊으셨나요?
Human: 코끼리가 제일 인상깊었어요
AI: 코끼리는 정말 멋진 동물이죠! 그들을 보고 무엇을 느꼈나요? 사진을 찍은 이유가 무엇인지 궁금해요.
Human: 코끼리 똥이 너무 커서 인상깊었어요. 근데 몸 크기를 보면 똥이 그렇게 큰게 이해가 되었어요. 정말이지 놀랐아요
AI: 그런 경험도 있군요! 코끼리의 똥이 정말 크다는 것을 보고 놀랐다니, 정말 특별한 경험이었겠죠. 사진을 찍은 이유가 무엇인지 궁금해요. 어떤 이야기가 담겨있나요?
Human: 저 사진은 코끼리 사진인데 코끼리는 코가 길어요~
AI: 코끼리의 긴 코도 정말 매력적이죠! 코끼리의 코가 길어서 무엇을 할 때 특히 유용한지 궁금해요. 사진을 찍은 이유가 무엇인지 더 자세히 알려주실 수 있나요?
Human: 똥이 너무 커서 찍었다니까요
AI: 그렇군요, 코끼리의 똥이 너무 커서 찍은 사진이군요! 그런 이유로 사진을 찍은 것을 이해합니다. 코끼리의 놀라운 특징들을 발견하고 기록하는 것도 정말 재미있는 경험이겠죠. 다른 동물들도 보셨을 때 어떤 점이 인상깊으셨나요?
Human: 미어캣이 너무 귀엽더라고요
AI: 미어캣은 정말 귀엽고 사랑스러운 동물이죠! 그들의 …
=> [Feat] 요약 작업 실행 #187

src/service/mystic/src/app/router/llm/chat.py, src/service/mystic/src/app/router/llm/connect.py, src/service/mystic/src/app/router/llm/disconnect.py, src/service/mystic/src/app/router/llm/image.py, src/service/mystic/src/chain/base/__init__.py
=> [Fix] Mystic 최종 수정 #201

src/service/nestjs/src/api/album/album.controller.ts, src/service/nestjs/src/api/diary/diary.controller.ts
- close #203 
-
DELETE /album/album_id 검증 결과
DELETE /diary/diary_id 검증 결과
- req.user.id 일치 여부 확인 로직 추가 했습니다.
=> [Secure] DELETE /album/album_id, /diary/diary_id Issue #203

src/service/mystic/src/app/router/stt/.cph/.__init__.py_b415019d1184818d0b5e06acd6991f5d.prob, src/service/mystic/src/app/router/stt/__init__.py, src/service/mystic/src/app/router/tts/__init__.py, src/service/mystic/src/model/stt/__init__.py, src/service/mystic/src/model/tts/__init__.py
- Mystic 작업 완료. 
- close #212 
- Frontend와 연동하며 발생한 STT, TTS 문제 해결
- TTS에 입력되는 Text의 특수문자 제거
-
=> [Fix] Frontend Mystic 연결 #212

README.md
=> [Feat] Main 페이지 Secure abstract 작성 #227

src/service/nextjs/src/app/(private)/album/page.tsx, src/service/nextjs/src/app/(private)/search/page.tsx, src/service/nextjs/src/app/(public)/auth/login/callback/page.tsx
=> [Fix] Install service worker #232

README.md
=> [Feat] README 수정 #234

src/service/mystic/src/model/llm/README.md, src/service/mystic/src/template/README.md
=> [Feat] LLM README 작성 #236

docs/CNAME, docs/_config.yml
=> [Fix] Fixing the CNAME file and the _config.yml file for the github pages

docs/_includes/head.html, docs/index.md
=> [Fix] github page css

docs/public/css/hyde.css
=> [Fix] background-color of code block

src/service/nextjs/src/component/audio-recorder/index.tsx, src/service/nextjs/src/container/(private)/diary/chat-interface/index.tsx, src/service/nextjs/src/container/(private)/diary/theme-select/theme/index.tsx
=> [Fix] Start beep timing #254

src/service/nextjs/src/app/(private)/album/page.tsx, src/service/nextjs/src/app/(public)/auth/login/callback/page.tsx, src/service/nextjs/src/container/(public)/auth/register/button/index.tsx
=> [Fix] Service worker install page #256

src/service/nextjs/src/container/(private)/diary/theme-select/index.tsx, src/service/nextjs/src/container/(private)/diary/theme-select/theme/index.tsx
=> [Feat] Shin-chan theme #258

src/service/mystic/src/app/router/stt/__init__.py
- close #252 
- STT Request 수정
- IOS 환경에서 webm이 아닌 mp4 format으로 음성파일을 넘기는 문제가 발생하여, STT Request에 type 추가
-
=> [Fix] STT Request fix #252
